### ISSUE TITLE
confused about permissions

### ISSUE THREAD

**Issue by mickleberry** [WesSouza/mastodon-flock#14]
Just looking at this app now, seems a great initiative... but i don't know how it's decided who i am on twitter. The app didn't ask for my twitter handle at all (i didn't authorise), but it knew where to look somehow.

**Comment by WesSouza** [comment]
I don't understand what you are referring to "how it's decided who i am on twitter", because the app doesn't ever show any Twitter details for the current account, only for accounts that it found that you follow, after you authorize.

This is the current flow for a cancelled Twitter authorization:

1. User visits the [Welcome step](https://mastodon-flock.vercel.app/), clicks "Next"
2. User visits the [Installation Method step](https://mastodon-flock.vercel.app/?step=chooseMethod), clicks "Next"
3. User is redirected to Twitter, clicks "Cancel"
4. If the user is logged in, they might see an extra Twitter step, then clicks "Return to Mastodon Flock"
5. User gets to the [Installation Method step](https://mastodon-flock.vercel.app/?step=chooseMethod)

Where are you seeing this "decided who i am on twitter"?

**Comment by mickleberry** [comment]
Hi 😺 Thanks for your reply Wes... 

What i meant is that i was not aware of authorising your app to use my twitter account at any point. I was not aware of telling the app at any point even what my twitter handle was... that's what i was talking about. 

But look **_i probably just missed that step_**, maybe i wasn't paying enough attention... As i return to your app now i can clearly see the page asking for authorization (on the twitter site) - and it just works out who i am because i'm signed in. So, probs my mistake tbh 

Thanks anyway
